### ISSUE TITLE
HostKey and HostKeyAlgorithms

### ISSUE THREAD

**Issue by lgrn** [k4yt3x/sshd_config#10]
Hi,

Maybe I'm missing something, but the combination of these two confuses me:

https://github.com/k4yt3x/sshd_config/blob/18a56d9adb099ac2f67161f4729ef03139726fdb/sshd_config#L105

https://github.com/k4yt3x/sshd_config/blob/18a56d9adb099ac2f67161f4729ef03139726fdb/sshd_config#L110

If `HostKey` is only set to use a key of type `ed25519`, wouldn't this make the `HostKeyAlgorithms` `rsa-sha2-512,rsa-sha2-256` unusable?

**Comment by k4yt3x** [comment]
You're right in that RSA would not be usable in this configuration. The motivation behind this was discussed here: https://github.com/k4yt3x/sshd_config/pull/9#discussion_r1574070736. It would be nice to change this to avoid confusion. Personally, I'd rather do something like accepting RSA keys but make it require a key >= 3072 bits. Haven't looked into the possibility of that.
