### ISSUE TITLE
关于 Kex 算法应以**必须**实现的算法保底的建议

### ISSUE THREAD

**Issue by IceCodeNew** [k4yt3x/sshd_config#2]
如题，我参考的文档是：https://tools.ietf.org/html/draft-ietf-curdle-ssh-kex-sha2-10#section-5 ，这里 `diffie-hellman-group14-sha256` 被标记为 `MUST`。
当然严格来说这个版本已经到期了，最新的草案应该是 https://tools.ietf.org/html/draft-ietf-curdle-ssh-kex-sha2-11 。不过这个版本的总结里已经找不到标记为 `MUST` 的算法，所以不便在一开头引用——尽管如此，这份草案里还是提到：
> It is believed that all current SSH implementations should be able to achieve an implementation of the "diffie-hellman-group14-sha256" method. To that end, this is one method that MUST be implemented.

**Comment by k4yt3x** [comment]
这个算法我原先的确是包括进去了的（参见 1.1 的 tag），在昨天的更新里我将所有算法全都替换成了 [ssh-audit 推荐的算法](https://github.com/jtesta/ssh-audit/tree/master/policies)，结果没注意检查 `diffie-hellman-group14-sha256` 居然被删了。

我刚刚重新检查了一下，连 ssh-audit 工具自己都说自家的 profile 漏了这个算法。我等下把 PR merge 掉然后把 ssh_config 那边也修改一下吧。（P.S. 我先睡一觉）
