### ISSUE TITLE
Wrong command to restart sshd

### ISSUE THREAD

**Issue by Dream4ever** [k4yt3x/sshd_config#6]
In the readme, there is a command `sudo systemctl restart ssh`, I think it should be `sudo systemctl restart sshd`. 😄

**Comment by k4yt3x** [comment]
On Debian machines, it's called `ssh`. On RHEL, CentOS, and some other distros, it's called `sshd`.
I'll add a note for it. Thanks.

**Comment by Dream4ever** [comment]
> On Debian machines, it's called `ssh`. On RHEL, CentOS, and some other distros, it's called `sshd`.
> I'll add a note for it. Thanks.

涨姿势了 👍
